Add option to run simpler WSGI app
geopython/pycsw pull request #829
Opened 2022-12-09 13:36 UTC by epifanio

Add option to run simpler WSGI app instead of flask  app in the docker entry-point

# Overview

Adds an entry in the configure to decide which app `wsgi` or `wsgi.flask` should run via the docker entrypoint

# Related Issue / Discussion

The flask app at the moment depends on the pycsw backend (e.g.: PostgreSQL, SQLite ) - the actual entrypoint doesn't have an option to run the simpler wsgi app to deploy a csw service

# Additional Information

# Contributions and Licensing

(as per https://github.com/geopython/pycsw/blob/master/CONTRIBUTING.rst#contributions-and-licensing)

- [x] I'd like to contribute [feature X|bugfix Y|docs|something else] to pycsw. I confirm that my contributions to pycsw will be compatible with the pycsw license guidelines at the time of contribution.
- [x] I have already previously agreed to the pycsw Contributions and Licensing Guidelines

2022-12-21 12:30 UTC, kalxas requested changes
Thanks for the PR, please review the comments.

2023-03-20 15:46 UTC, epifanio commented
@tomkralidis - can we look into this?

2023-03-31 11:41 UTC, frafra commented
I tried to add some comments, since feedback has been requested on the gitter channel.

I am trying to get my head around the Dockerfile. Why the code to start pycsw is in an entrypoint in the first place?

2023-04-02 09:27 UTC, epifanio commented
In this change i simply bypass the db settings/connection as it is not required to run the CSW services. Which makes the code more likely a standard docker entry point. Perhaps the db settings should go into the flask app itself?

2023-09-29 15:59 UTC, tomkralidis commented
Closing in lieu of #907

2023-09-29 15:59 UTC, closed without merging