[WIP] update configuration to YAML
geopython/pycsw pull request #937
Opened 2024-01-05 05:46 UTC by tomkralidis

# Overview
Updates pycsw configuration from ini to YAML.

# Related Issue / Discussion
Fixes #797
# Additional Information

# Contributions and Licensing

(as per https://github.com/geopython/pycsw/blob/master/CONTRIBUTING.rst#contributions-and-licensing)

- [x] I'd like to contribute [feature X|bugfix Y|docs|something else] to pycsw. I confirm that my contributions to pycsw will be compatible with the pycsw license guidelines at the time of contribution.
- [x] I have already previously agreed to the pycsw Contributions and Licensing Guidelines

2024-01-05 12:34 UTC, kalxas commented
We will also need to update the kubernetes helm charts when this is merged

2024-01-05 15:57 UTC, tomkralidis commented
k8s and helm charts first pass updated as part of this PR.

2024-01-06 02:44 UTC, tomkralidis commented
- migration script added
- associated demo update PR in https://github.com/geopython/demo.pycsw.org/pull/10

2024-01-06 10:26 UTC, kalxas requested changes
Excellent work!

2024-01-06 10:26 UTC, kalxas commented on docker/helm/templates/pycsw-configmap.yaml
> +    repositor:
typo: should be repository

2024-01-06 10:26 UTC, kalxas commented on docker/helm/templates/pycsw-configmap.yaml
> +{{ end }}{{ if .Values.pycsw.config.metadata.identification.keywords }}        keywords: {{ .Values.pycsw.config.metadata.identification.keywords }}
Need to test if keywords are dumped in yaml style here

2024-01-06 10:29 UTC, kalxas commented on docker/helm/templates/pycsw-configmap.yaml
> +    repositor:
Fixed

2024-01-06 13:43 UTC, kalxas approved these changes

2024-01-06 15:27 UTC, merged

2024-01-07 15:35 UTC, pvgenuchten commented
Nice work, just to confirm: the override mechanism with environmental variables is still supported?

2024-01-07 15:44 UTC, tomkralidis commented
@pvgenuchten yes, environment variables are interpreted as per before.